version: "3.5"

services:
  mariadb:
    image: mariadb:10.10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: strapi
      MARIADB_DATABASE: strapi
      MARIADB_USER: strapi
      MARIADB_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes:
      - .docker/data/mariadb:/var/lib/mysql

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - 5432:5432
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data

  adminer:
    image: dockette/adminer:dg
    restart: always
    ports:
      - 8080:80
